spring.application.name=backend

# 로컬 개발용 PostgreSQL (Docker) 접속 정보
spring.datasource.url=jdbc:postgresql://localhost:5432/gagyebu
spring.datasource.username=gagyebu
spring.datasource.password=gagyebu1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
